---
- name: Install Unzip
  apt:
    name: unzip
    state: present

- name: Create java directory
  file:
    path: "{{ java_install_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download JDK tarball
  local_action: get_url url="{{ java_remote_source_url }}/{{ java_archive }}" dest="{{ java_staging_dir }}/{{ java_archive }}"
  become: False
  run_once: True

- name: Copy JDK tarball
  copy:
    src: "{{ java_staging_dir }}/{{ java_archive }}"
    dest: "{{ java_temp_dir }}/{{ java_archive }}"
    owner: root
    group: root
    mode: 0755

- name: Unpack JDK tarball
  unarchive:
    src: "{{ java_temp_dir }}/{{ java_archive }}"
    dest: "{{ java_install_dir }}"
    remote_src: yes
    owner: root
    group: root
    creates: "{{ java_real_home }}"

- name: Install Alternatives
  alternatives:
    name: java-home-link
    link: "{{ java_home }}"
    path: "{{ java_real_home }}"
    priority: 30

- name: Symlink Java
  file:
    dest: /usr/bin/java
    src: "{{ java_real_home }}/bin/java"
    state: link
    owner: root
    group: root

- name: Set default JAVA_HOME
  template: >
    src=java.sh.j2
    dest=/etc/profile.d/java.sh
    mode=644
    owner=root
    group=root
