---
- name: Create java directory
  file:
    path: "{{ java_install_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Download JDK tarball
  get_url:
    url: "{{ java_source_url }}/{{ java_archive }}"
    dest: "{{ java_temp_dir }}"
    headers: "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"

- name: Unpack JDK tarball
  unarchive:
    src: "{{ java_temp_dir }}/{{ java_archive }}"
    dest: "{{ java_install_dir }}"
    remote_src: yes
    owner: root
    group: root
    creates: "{{ java_real_home }}"

- name: Install Alternatives
  alternatives:
    name: java-home-link
    link: "{{ java_home }}"
    path: "{{ java_real_home }}"
    priority: 30

- name: Symlink Java
  file:
    dest: /usr/bin/java
    src: "{{ java_real_home }}/bin/java"
    state: link
    owner: root
    group: root

- name: Set default JAVA_HOME
  template: >
    src=java.sh.j2
    dest=/etc/profile.d/java.sh
    mode=644
    owner=root
    group=root
